server:
  port: 8085
spring:
  application:
    name: CONFIG-SERVER
    
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Priyanshu-Garg/microservice-config-server
          clone-on-start: true